config/routes.rb
Rails.application.routes.draw do

   root 'home#index'
   resources :inventories
   resources :marketings
   resources :customers

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
end

app/models/marketing.rb
class Marketing < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def index
	    @customers=Customer.all
		
		if params[:number].present?
		@customers=@customers.where("number like?","#{params[:number]}")
	    end

	end


    
    def edit
    	@customer=Customer.find(params[:id])
    end


    def show
	   @customer=Customer.find(params[:id])
	end

	def new
      @customer=Customer.new
	end


	def create
		@customer = Customer.new(customer_params)
		if @customer.save
			redirect_to customers_path 
		else
			render :new
		end
	end



    def update
        @customer=Customer.find(params[:id])
        if @customer.update(customer_params)
        	redirect_to customers_path
        else
        	render :edit
        end
    end

	private

    def destroy
    	@customer=Customer.find(params[:id])
    	@customer.destroy
    	redirect_to root_path
    end
	def customer_params
		params.require(:customer).permit(:number,:cusname,:product,:location,:frequency)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def new
	end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
	
    def index
		@inventories=Inventory.all
		if params[:number].present?
		@inventories=@inventories.where("number like?","#{params[:number]}")
	    end
	    if params[:location].present?
		@inventories=@inventories.where("location like?","#{params[:location]}")
	    end
     end


    def edit
    	@inventory=Inventory.find(params[:id])
    end

    def show
	   @inventory=Inventory.find(params[:id])
	end

	def new
      @inventory=Inventory.new
	end


	def create
		@inventory = Inventory.new(inventory_params)
		if @inventory.save
			redirect_to root_path 
		else
			render :new
		end
	end



    def update
        @inventory=Inventory.find(params[:id])
        if @inventory.update(inventory_params)
        	redirect_to inventories_path
        else
        	render :edit
        end
    end

	private

    def destroy
    	@inventory=Inventory.find(params[:id])
    	@inventory.destroy
    	redirect_to root_path
    end
	def inventory_params
		params.require(:inventory).permit(:number,:location,:name,:sales,:stock)
    end
end

app/controllers/marketings_controller.rb
class MarketingsController < ApplicationController
	
	def index
	    @marketings=Marketing.all
		
		if params[:number].present?
		@marketings=@marketings.where("number like?","#{params[:number]}")
	    end

	end

    
    
    def edit
    	@marketing=Marketing.find(params[:id])
    end


    def show
	   @marketing=Marketing.find(params[:id])
	end

	def new
      @marketing=Marketing.new
	end


	def create
		@marketing = Marketing.new(marketing_params)
		if @marketing.save
			redirect_to marketings_path 
		else
			render :new
		end
	end



    def update
        @marketing=Marketing.find(params[:id])
        if @marketing.update(marketing_params)
        	redirect_to marketings_path
        else
        	render :edit
        end
    end

	private

    def destroy
    	@marketing=Marketing.find(params[:id])
    	@marketing.destroy
    	redirect_to root_path
    end
	def marketing_params
		params.require(:marketing).permit(:number,:name,:time,:sales,:suggestion,:avr_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/marketings_helper.rb
module MarketingsHelper
end

app/views/customers/edit.html.erb
<h2>更新顧客資訊 </h2>
<%= form_for @customer do |f|%>

<div>
顧客編號
<%=f.text_field :number %>
</div>

<div>
顧客名稱
<%=f.text_field :cusname %>
</div>

<div>
最常消費商品
<%=f.text_field :product%>
</div>

<div>
最常消費門市
<%=f.text_field :location %>
</div>

<div>
總消費次數
<%=f.text_field :frequency %>
</div>


<%=f.submit%>

<% end -%>

app/views/customers/index.html.erb
<h1 style="text-align:center">顧客管理系統</h1>

<%=form_tag customers_path,method:"get" do%>
<h2 style="text-align:center">
顧客編號<%=text_field_tag :number%>
<%=submit_tag "搜尋"%>
</h2>
<% end -%>
<h2 style="text-align:center">  <%= link_to "新增顧客資訊", new_customer_path %>
</h2>

<% @customers.each do|customer|%>
<h2 style="text-align:center">
<%= link_to  customer.number, customer_path(customer) %>
<%= link_to  "更新顧客資訊", edit_customer_path(customer) %>
<%= link_to  "刪除顧客資訊", customer_path(customer) %>
</h2>
<% end %>

app/views/customers/new.html.erb
<h2>新增顧客資訊</h2>
<%= form_for @customer do|f|%>

<div>
顧客編號
<%=f.text_field :number %>
</div>


<div>
顧客名稱
<%=f.text_field :cusname %>
</div>

<div>
最常消費商品
<%=f.text_field :product%>
</div>

<div>
最常消費門市
<%=f.text_field :location %>
</div>


<div>
總消費次數
<%=f.text_field :frequency %>
</div>

<%=f.submit%>

<% end -%>

app/views/customers/show.html.erb
<h2 style="text-align:center">檢視顧客資訊</h2>

<h2 style="text-align:center">顧客編號： <%= @customer.number%> </h2>

<h2 style="text-align:center">顧客名稱： <%= @customer.cusname%></h2>

<h2 style="text-align:center">最常消費產品： <%= @customer.product%></h2>

<h2 style="text-align:center">最常消費門市： <%= @customer.location%></h2>

<h2 style="text-align:center">總消費次數： <%= @customer.frequency%></h2>

app/views/home/index.html.erb
<h2 style="text-align:center">星巴克作業管理系統</h2>
<div style="text-align:center" >
 <img  src=" http://buy.goodlife.tw/system/files/9506/original/STARBUCKS形象-e1429780322536.jpg?1450926694 " height="180" width ="280" %>
 </div>
 <div ><h2 style="text-align:center">
<%= link_to "新增存貨", new_inventory_path %>
</h2></div>
<div ><h2 style="text-align:center">
<%= link_to "存貨管理系統", inventories_path %>
</h2></div>
<div ><h2 style="text-align:center">
<%= link_to "行銷資訊系統", marketings_path %>
</h2></div>

<div ><h2 style="text-align:center">
<%= link_to "顧客管理系統", customers_path %>
</h2></div>

app/views/inventories/edit.html.erb
<h2>更新存貨 </h2>
<%= form_for @inventory do |f|%>

<div>
編號
<%=f.text_field :number %>
</div>


<div>
產品名稱
<%=f.text_field :name %>
</div>

<div>
地點
<%=f.text_field :location %>
</div>



<div>
平均每日銷售數量
<%=f.text_field :sales %>
</div>


<div>
剩餘庫存數量
<%=f.text_field :stock %>
</div>


<%=f.submit%>

<% end -%>

app/views/inventories/index.html.erb
<h1 style="text-align:center">存貨管理系統</h1>

<%=form_tag inventories_path,method:"get" do%>
<h2 style="text-align:center" >
商品編號<%=text_field_tag :number%>
分店<%=text_field_tag :location%>
<%=submit_tag "搜尋"%>
</h2>
<% end -%>

<% @inventories.each do|inventory|%>
<h2 style="text-align:center">
<%= link_to inventory.number, inventory_path(inventory) %>
<%= link_to "更新存貨", edit_inventory_path(inventory) %>
<%= link_to "刪除存貨", inventory_path(inventory) %>
</h2>
<% end %>

app/views/inventories/new.html.erb
<h2>新增存貨</h2>
<%= form_for @inventory do|f|%>

<div>
編號
<%=f.text_field :number %>
</div>


<div>
產品名稱
<%=f.text_field :name %>
</div>

<div>
地點
<%=f.text_field :location %>
</div>


<div>
平均每日銷售數量
<%=f.text_field :sales %>
</div>


<div>
剩餘庫存數量
<%=f.text_field :stock %>
</div>




<%=f.submit%>

<% end -%>

app/views/inventories/show.html.erb
<h2 style="text-align:center">檢視存貨</h2>

<h2 style="text-align:center">存貨編號： <%= @inventory.number%> </h2>

<h2 style="text-align:center">貨品名稱： <%= @inventory.name%> </h2>

<h2 style="text-align:center">門市： <%= @inventory.location%></h2>


<h2 style="text-align:center">每日平均銷售數量： <%= @inventory.sales%></h2>

<h2 style="text-align:center">剩餘庫存： <%= @inventory.stock%></h2>

<h2 style="text-align:center">進貨建議：
<% if @inventory.stock / @inventory.sales < 6 ; @inventory.stock / @inventory.sales > 5%>
    明天需要申請補貨！
<% elsif @inventory.stock / @inventory.sales < 5 %>
   需要馬上申請補貨！
 <%else%>
    離需要申請補貨時間 尚有兩天以上
<%end%>

</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container'>
<%= yield %>
</div>
</body>
</html>

app/views/marketings/edit.html.erb
<h2>更新存貨 </h2>
<%= form_for @marketing do |f|%>

<div>
編號
<%=f.text_field :number %>
</div>

<div>
名稱
<%=f.text_field :name %>
</div>

<div>
時間區間
<%=f.text_field :time%>
</div>

<div>
銷售量
<%=f.text_field :sales %>
</div>


<div>
過去12個月平均銷售輛
<%=f.text_field :avr_number %>
</div>


<%=f.submit%>

<% end -%>

app/views/marketings/index.html.erb
<h2 style="text-align:center">行銷資訊系統</h2>

<%=form_tag marketings_path,method:"get" do%>
<h2 style="text-align:center">
商品編號<%=text_field_tag :number%>
<%=submit_tag "搜尋"%>
</h2>
<% end -%>
<h2 style="text-align:center ">
<%= link_to "新增存貨", new_marketing_path %>
</h2>
<% @marketings.each do|marketing|%>
<h2 style="text-align:center">
<%= link_to marketing.number, marketing_path(marketing) %>
<%= link_to "更新存貨", edit_marketing_path(marketing) %>
<%= link_to "刪除存貨", marketing_path(marketing) %>
</h2>
<% end %>

app/views/marketings/new.html.erb
<h2>新增存貨</h2>
<%= form_for @marketing do|f|%>

<div>
編號
<%=f.text_field :number %>
</div>


<div>
名稱
<%=f.text_field :name %>
</div>

<div>
時間區間
<%=f.text_field :time%>
</div>

<div>
銷售量
<%=f.text_field :sales %>
</div>


<div>
過去12個月平均銷售量
<%=f.text_field :avr_number %>
</div>


<%=f.submit%>

<% end -%>

app/views/marketings/show.html.erb
<h2 style="text-align:center">檢視存貨</h2>

<h2 style="text-align:center">產品編號： <%= @marketing.number%> </h2>

<h2 style="text-align:center">產品名稱： <%= @marketing.name%></h2>

<h2 style="text-align:center">時間區間： <%= @marketing.time%></h2>

<h2 style="text-align:center">銷售量： <%= @marketing.sales%></h2>

<h2 style="text-align:center">過去12個月平均銷售量： <%= @marketing.avr_number%></h2>

<h2 style="text-align:center"> 行銷建議： <%= @marketing.suggestion%></h2>
<h2 style="text-align:center">
<%if @marketing.avr_number - @marketing.sales > 0 %>
買一送一刺激買氣
<%else%>
在各大廣告平台進行進一步推廣
<%end%>
</h2>